# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "Tips and Tutorials"
author:
  name: Christian Weiß 
  github: wechris
description: "Useful tips and tutorials for blogging and other sections such as Photography, SAP, HTML, etc."
baseurl: "/tips-tutorials" # the subpath of your site, e.g. /blog
url: "https://wechris.github.io" # the base hostname & protocol for your site

logo:
  path: "/img/favicons/android-chrome-192x192.png"
  width: 192
  height: 192

# Build settings
paginate: 10 # the number of post per page
highlighter: rouge
markdown: kramdown
permalink: pretty

sass:
  sass_dir: _sass
  style: compressed # Possible values -> nested / expanded / compact / compressed

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed

# Handling Reading
exclude:
  - "README.md"
  - "LICENSE"
